set nocompatible

syntax on

set hlsearch

set autoindent
set smartindent
set wildmenu

let mapleader=","

set number
:nnoremap <leader>n :set invnumber<Enter>

set nobackup
set nowb
set noswapfile


"save, clear console and execute current file
:nnoremap <F9> :update"%:p"<Enter>:!clear&&"%:p"<Enter>

:nnoremap <leader>s :w<Enter>

:nnoremap <leader>q :wq<Enter>

:nnoremap <leader><leader>q :q!<Enter>

:nnoremap <leader>e :Explore<Enter>

:nnoremap <leader><leader>b :bdelete<Enter>

" split
:nnoremap <leader>v :vsp<Enter>
:nnoremap <leader>h :sp<Enter>



" set cursor to solid vertical bar when in insert mode
let &t_SI .= "\<Esc>[6 q"
" set cursor to solid block when in normal mode
let &t_EI .= "\<Esc>[2 q"
